; put in gimp scripts directory and call it like this
; gimp -i -b '(gimp_cycle_gif_colors "image.gif" cycles frequency)' -b '(gimp-quit 0)'
; "cycles" is how many times you want to cycle through colours (for long gifs)
; "frequency" determines the intensity of the colours (set it to 1 if you're not sure
; gifs must be unoptomized. To unoptomize gifs in gimp, use filters>animation>unoptimize
(define (gimp_cycle_gif_colors filename loops frequency)
  (let* ((image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
     (rawlayers (gimp-image-get-layers image))
     (nlayers (car rawlayers))
     (layers (cadr rawlayers))
     (drawable (car (gimp-image-get-active-layer image)))
     (i 0))
        (gimp-image-convert-rgb image)
        (while (< i nlayers)
            (gimp-image-set-active-layer image (aref layers i))
            (plug-in-alienmap2 RUN-NONINTERACTIVE image (car (gimp-image-get-active-layer image))
                               frequency (/ (* i 360 loops) nlayers)
                               frequency (+ (/ (* i 360 loops) nlayers) 180)
                               frequency (- 360 (/ (* i 360 loops) nlayers))
                               0 TRUE TRUE TRUE)
            (set! i (+ i 1))
        )
        (gimp-image-convert-indexed image 0 0 255 FALSE FALSE "palette")
        (file-gif-save RUN-NONINTERACTIVE image drawable filename filename 0 1 50 0)
        (gimp-image-delete image)
  )
)
